name: Terraform Workflow

on: 
    push

jobs:
    terraform:            
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
              
            - name: Terraform Init             
              run: terraform init

            - name: Terraform Validate
              run: terraform validate

            - name: Terraform Plan
              run: terraform plan

            